# Codebook

This document explains the content of 'samsungtidydataset.txt' file generated by the 'run_analysis.R' R script in order to make the data avaliable at https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip a tidy dataset.

## Variables

**WARNNING: ** To make sure that you'll be able to understand the meaning of all variables, I strongly recommend you to previously download and unzip the original zip file at https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip and read the content of 'README.txt' and 'features_info.txt' files.

The description of 'samsungtidydataset.txt' variables are as follows:
* "Subject id": is the id of the person who performed the activity
* "Activity name": is the name of the activity that was performed
All the others variables has the same meaning as described into 'features_info.txt' file. The content value of these variables are the mean calculos of itself, grouped by the subject and by the activity.